### ISSUE TITLE
Зачем java?

### ISSUE THREAD

**Issue by pumbaEO** [bytemdfab/decompiler-1c#1]
onescript или даже обработка на 8 , т.к. все равно в конечном итоге необходимо запускать 1с.

**Comment by bytemdfab** [comment]
Вот так всегда - что-то начинаешь делать, и тут находишь готовое решение :) С полгода назад реализовал все на ant файлах, с вставками на jython (для раскладывания по папкам). Теперь вот присматриваюсь к onescript.

**Comment by pumbaEO** [comment]
https://github.com/xDrivenDevelopment/v83unpack обработка на 1с, для linux есть ветка с одноименным названием, для onescript ветка develop

**Comment by bytemdfab** [comment]
Спасибо за наводки, буду разбираться.
